name: Terraformar

on:
  push:
    branches: [ main ]         # ou as que você permitir na trust policy
  workflow_dispatch:

permissions:
  id-token: write              # OBRIGATÓRIO p/ OIDC
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar credenciais da AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::935194211887:role/GitHubActionsTerraformRole
          role-session-name: gha-terraform
          aws-region: us-east-1

      # (seus passos de terraform init/plan/apply)
