name: Terraformar

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_IN_AUTOMATION: "true"
      AWS_REGION: us-east-1
    defaults:
      run:
        working-directory: nextcloud-aws-terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 0

      - name: Debug ref (optional)
        run: |
          echo "repo=${{ github.repository }}"
          echo "ref=${{ github.ref }}"
          echo "event=${{ github.event_name }}"

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::935194211887:role/GitHubActionsTerraformRole
          role-session-name: gha-terraform
          aws-region: us-east-1
          output-credentials: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.7

      - name: Cache .terraform providers
        uses: actions/cache@v4
        with:
          path: |
            ~/.terraform.d/plugin-cache
            nextcloud-aws-terraform/.terraform
          key: ${{ runner.os }}-tf-${{ hashFiles('nextcloud-aws-terraform/**/*.tf') }}
          restore-keys: |
            ${{ runner.os }}-tf-

      - name: Terraform fmt (check)
        working-directory: nextcloud-aws-terraform
        run: terraform fmt -check -recursive

      - name: Terraform init
        working-directory: nextcloud-aws-terraform
        run: terraform init -input=false

      - name: Terraform validate
        working-directory: nextcloud-aws-terraform
        run: terraform validate -no-color

      - name: Terraform plan
        working-directory: nextcloud-aws-terraform
        run: terraform plan -input=false

      - name: Terraform apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch'
        working-directory: nextcloud-aws-terraform
        run: terraform apply -auto-approve -input=false

      - env:
        tf_plugin_cache_dir: ~/.terraform.d/plugin-cache



