name: Terraformar

on:
  push:
    branches: [ main ]         # ajuste se quiser permitir outras branches
  workflow_dispatch:

permissions:
  id-token: write              # OBRIGATÓRIO p/ OIDC
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar credenciais da AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::935194211887:role/GitHubActionsTerraformRole
          role-session-name: gha-terraform
          aws-region: us-east-1

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.7

      - name: Terraform Init
        run: terraform -chdir=infra init -input=false

      - name: Terraform Plan
        run: terraform -chdir=infra plan -input=false

      # Opcional — aplicar apenas em push ou manual
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch'
        run: terraform -chdir=infra apply -auto-approve -input=false
